### ISSUE TITLE
access Funktion funktioniert nicht richtig

### ISSUE THREAD

**Issue by openpvs** [MisterNSA/Daten-Exporter#3]
Die access Funktion soll überprüfen ob eine Datei von einem andere Prozess geöffnet ist und somit nicht aus dem zu überwachenden Ordner verschoben werden darf. Das tut sie aber nicht und wenn eine Datei durch einen anderen Prozess geöffnet ist endet das in einem Fehler mit Programmabbruch.

**Comment by MisterNSA** [comment]
Ich habe es vorher mit "w" geöffnet, allerdings wird der Inhalt dann neu geschrieben, bzw. ohne Wert, gelöscht. Ich verstehe das Problem mal, dass in der Zeit nach dem Test eine anderes Programm zugreifen kann.  

Habe etwas nachgedacht und nachgeforscht. 
Ich denke, das Sinnvollste wird sein, die CheckAccess Funktion zu löschen und mittels locking neu zu schreiben. 

Am Anfang versuche ich die File zu locken, wenn nicht, continue. Wenn sie sich locken lässt, alle Operationen ausführen und letztendlich entlocken. Falls ich die gelockte Datei nicht verschieben kann, an Zielort kopieren und anschließend alte Datei löschen.

Werde deshalb mal schauen, ob ich eine der Möglichkeiten verstehe...

**Comment by MisterNSA** [comment]
Ich tue einfach mal so, als hätte ich es gelöst. Ich vertraue der Methode die Datei in sich selbst umzubenennen zwar nicht, aber ich lasse mich gerne vom Gegenteil überzeugen.
